uSync.Migrations/Composing/SyncMigrationProfileCollectionBuilder.cs, uSync.Migrations/Composing/SyncMigrationsComposer.cs, uSync.Migrations/Configuration/CoreProfiles/ContentMigrationProfile.cs, uSync.Migrations/Configuration/CoreProfiles/EverythingMigrationProfile.cs, uSync.Migrations/Configuration/CoreProfiles/SettingsMigrationProfile.cs, uSync.Migrations/wwwroot/uSyncMigrations/Lang/en-us.xml, uSync.Migrations/wwwroot/uSyncMigrations/dashboard.html
make sure the profiles appear in an order (made it a weighted collection).
=> Order the profiles correctly.

uSync.Migrations/wwwroot/uSyncMigrations/Lang/en-us.xml, uSync.Migrations/wwwroot/uSyncMigrations/migrate.controller.js, uSync.Migrations/wwwroot/uSyncMigrations/migrate.html
put a "nice" error box on the migrate page so at least people might know something has gone wrong.
=> error box on the migrations dashboard

README.md, uSync.Migrations/Migrators/Core/ColorPickerMigrator.cs, uSync.Migrations/Validation/FileStructureValidator.cs, uSync.Migrations/wwwroot/uSyncMigrations/Lang/en-us.xml, uSync.Migrations/wwwroot/uSyncMigrations/dialogs/handlerPicker.html, uSync.Migrations/wwwroot/uSyncMigrations/migrate.html
My usual, small typos I'd spotted along the way, _(with love)_ 🤗
=> Corrected typos

uSync.Migrations/Composing/SyncMigrationProfileCollectionBuilder.cs, uSync.Migrations/Composing/SyncMigrationValidatorCollection.cs, uSync.Migrations/Composing/SyncMigrationsComposer.cs, uSync.Migrations/Configuration/CoreProfiles/ContentMigrationProfile.cs, uSync.Migrations/Configuration/CoreProfiles/EverythingMigrationProfile.cs, uSync.Migrations/Configuration/CoreProfiles/SettingsMigrationProfile.cs, uSync.Migrations/Configuration/ISyncMigrationConfigurationService.cs, uSync.Migrations/Configuration/Models/ISyncMigrationProfile.cs, uSync.Migrations/Configuration/Models/MigrationOptions.cs, uSync.Migrations/Configuration/Models/MigrationProfile.cs, uSync.Migrations/Configuration/Models/MigratrionProfileConfig.cs, uSync.Migrations/Configuration/SyncMigrationConfigurationService.cs, uSync.Migrations/Controllers/uSyncFilesTreeController.cs, uSync.Migrations/Controllers/uSyncMigrationsController.cs, uSync.Migrations/Handlers/DataTypeMigrationHandler.cs, uSync.Migrations/Handlers/DictionaryMigrationHandler.cs, uSync.Migrations/Handlers/TemplateMigrationHandler.cs, uSync.Migrations/Migrators/Community/VortoMapper.cs, uSync.Migrations/Migrators/Core/ColorPickerMigrator.cs, uSync.Migrations/Migrators/Core/SliderMigrator.cs, uSync.Migrations/Models/SyncMigrationContext.cs, uSync.Migrations/Services/ISyncMigrationFileService.cs, uSync.Migrations/Services/ISyncMigrationService.cs, uSync.Migrations/Services/SyncMigrationFileService.cs, uSync.Migrations/Services/SyncMigrationService.cs, uSync.Migrations/uSyncMigrations.cs, uSync.Migrations/wwwroot/uSyncMigrations/dashboard.html, uSync.Migrations/wwwroot/uSyncMigrations/dialogs/handlerPicker.html, uSync.Migrations/wwwroot/uSyncMigrations/migrate.html
These are the ones where I annoy code maintainers the most, sorry - call it OCD, but felt the need for whitespace consistency.
=> Whitespace formatting

uSync.Migrations/Configuration/SyncMigrationConfigurationService.cs, uSync.Migrations/Controllers/uSyncMigrationsController.cs, uSync.Migrations/Extensions/PreValueExtensions.cs, uSync.Migrations/Migrators/SyncPropertyMigratorBase.cs, uSync.Migrations/Services/SyncMigrationFileService.cs
Another one of my typical "odds & sods" branches, just little things I'd spotted and corrected, up to you. 🤗
=> Various code formatting

uSync.Migrations/Extensions/PreValueExtensions.cs, uSync.Migrations/Migrators/Community/uEditorNotesToContentmentEditorNotes.cs, uSync.Migrations/Migrators/Community/uEditorNotesTouEditorNotes.cs
And also one that will go to the even more popular Contentment one
=> Add support for the popular uEditorNotes property editor

uSync.Migrations/Migrators/Core/NestedContentMigrator.cs
To fix this issue, I just added a "?" to pass null, if the property does not have value
=> NestedContent: Property value can be null, resulting in an error

uSync.Migrations.Tests/Migrators/ColourPickerMigratorTests.cs, uSync.Migrations/Extensions/ContentTypeExtensions.cs, uSync.Migrations/Migrators/BlockGrid/BlockMigrators/DocTypeGridEditorBlockMigrator.cs, uSync.Migrations/Migrators/BlockGrid/BlockMigrators/GridMediaBlockMigrator.cs, uSync.Migrations/Migrators/Core/NestedContentMigrator.cs, uSync.Migrations/Migrators/Models/SyncMigrationContentProperty.cs
removing some warnings - from the build.
=> tidy up some null checking stuff before builds.

uSync.Migrations/Migrators/Community/NuPickersEnumCheckBoxPickerToContentmentDataList.cs, uSync.Migrations/Migrators/Community/NuPickersSqlDropdownPickerToContentmentDataList.cs, uSync.Migrations/Migrators/Community/NuPickersXPathCheckboxPickerToContentmentDataList .cs, uSync.Migrations/Migrators/Community/NuPickersXPathDropdownPickerToContentmentDataList.cs, uSync.Migrations/Migrators/Models/NuPickers/NuPickersEnumConfig.cs, uSync.Migrations/Migrators/Models/NuPickers/NuPickersSqlConfig.cs, uSync.Migrations/Migrators/Models/NuPickers/NuPickersXmlConfig.cs
A start on the NuPickers data types.  These migrate to contentment data types at the moment.
=> Some NuPickers Migrators to Contentment data types

uSync.Migrations/Migrators/Community/ImulusUrlPickerToUmbMultiUrlPickerMigrator.cs, uSync.Migrations/Migrators/Models/UrlPicker/UrlPicker.cs, uSync.Migrations/Migrators/Models/UrlPicker/UrlPickerMeta.cs, uSync.Migrations/Migrators/Models/UrlPicker/UrlPickerTypeData.cs, uSync.Migrations/Migrators/Models/UrlPicker/UrlPickerTypes.cs, uSync.Migrations/Migrators/Models/UrlPicker/UrlPickerValue.cs
=> Migrator for Imulus URL Picker

uSync.Migrations/Handlers/Seven/ContentTypeBaseMigrationHandler.cs
Also, setting the tab to a "tab" rather than group.  Think this could do with a way of setting in config or similar though.
=> Tabs sometimes don't have GUID's

uSync.Migrations/Migrators/Community/NuPickersEnumCheckBoxPickerToContentmentDataList.cs, uSync.Migrations/Migrators/Community/NuPickersEnumDropDownPickerToContentmentDataList.cs
Add nuPickers EnumDropDownPicker migrator and fix the config of the EnumCheckBoxPicker migrator
=> Add nuPickers EnumDropDownPicker migrator

.github/workflows/dotnet.yml, .github/workflows/release-nuget.yml, uSync.Migrations/Migrators/Core/DropdownMigrator.cs
fixed dropdown migrator so it has a 0 based index for the id rather than relying on the sort order which sometimes causes errors
=> fixed dropdown migrator so it has a 0 based index for the id

uSync.Migrations/Migrators/Community/ImulusUrlPickerToUmbMultiUrlPickerMigrator.cs
Fix Imulus picker to also work when stored in an array.  #84
=> Fix - imulus picker , to work when multiple items are set.

uSync.Migrations/Migrators/Core/NestedContentMigrator.cs, uSync.Migrations/Migrators/Optional/NestedToBlockListMigrator.cs
Better logging for nested content
=> Nested content - Catching errors - reporting them back meaningfully.

GETTING-STARTED.md
I'm waging a bet that you knew I'd do this! 😅
=> Getting Started - corrected typos

GETTING-STARTED.md
Following on from #142, I missed a typo correction. 🤦
=> Getting Started - corrected another typo I'd missed

uSync.Migrations/Extensions/GuidExtensions.cs, uSync.Migrations/Migrators/Core/RelatedLinksMigrator.cs, uSync.Migrations/Migrators/Core/RichTextBoxMigrator.cs
Added improved regex and pass the grouped result through to method that encapsulates GUID with quotes.
=> #145 - fixed related links migrator 

uSync.Migrations/Handlers/Shared/SharedContentTypeBaseHandler.cs
All of the split properties were trying to use the same (original) property key. This PR ensures they are unique for each split property.
=> Fix issue causing split properties to use duplicate property key

uSync.Migrations/Migrators/Core/RadioButtonListMigrator.cs
Basically the fix from your reply @KevinJump
https://github.com/Jumoo/uSyncMigrations/issues/113#issuecomment-1582682734
=> RadioButtonList - Fixes #113, migrated value

GETTING-STARTED.md, uSync.Migrations.Tests/Migrators/CheckboxListTests.cs, uSync.Migrations.Tests/Migrators/ColourPickerMigratorTests.cs, uSync.Migrations.Tests/Migrators/MigratorTestBase.cs, uSync.Migrations.Tests/Migrators/RadioButtonListTests.cs, uSync.Migrations.Tests/Migrators/TextBoxMigratorTests.cs, uSync.Migrations.Tests/Migrators/TrueFalseMigratorTests.cs, uSync.Migrations/Composing/SyncPropertyMigratorCollectionBuilder.cs, uSync.Migrations/Context/MigratorsContext.cs, uSync.Migrations/Extensions/GuidExtensions.cs, uSync.Migrations/Handlers/MigrationHandlerBase.cs, uSync.Migrations/Handlers/Shared/SharedContentBaseHandler.cs, uSync.Migrations/Handlers/Shared/SharedContentTypeBaseHandler.cs, uSync.Migrations/Migrators/BlockGrid/BlockMigrators/GridMediaBlockMigrator.cs, uSync.Migrations/Migrators/BlockGrid/Config/GridToBlockGridConfigLayoutBlockHelper.cs, uSync.Migrations/Migrators/BlockGrid/Content/GridToBlockContentHelper.cs, uSync.Migrations/Migrators/Community/Archetype/ArchetypeToBlockListMigrator.cs, uSync.Migrations/Migrators/Community/NuPickersToContentmentDataListBase.cs, uSync.Migrations/Migrators/Community/NuPickersXPathCheckboxPickerToContentmentDataList .cs, uSync.Migrations/Migrators/Community/NuPickersXPathDropdownPickerToContentmentDataList.cs, uSync.Migrations/Migrators/Community/StackedContentToBlockListMigrator.cs, uSync.Migrations/Migrators/Community/VortoMapper.cs, uSync.Migrations/Migrators/Core/NestedContentMigrator.cs, uSync.Migrations/Migrators/Core/RadioButtonListMigrator.cs, uSync.Migrations/Migrators/Core/RelatedLinksMigrator.cs, uSync.Migrations/Migrators/Core/RichTextBoxMigrator.cs, uSync.Migrations/Migrators/Optional/NestedToBlockListMigrator.cs, uSync.Migrations/Services/SyncMigrationService.cs, uSync.Migrations/Services/SyncMigrationStatusService.cs, uSync.Migrations/wwwroot/uSyncMigrations/components/migrationResults.html
This is a PR for your current PR #149.
But with all my amends, and the latest `main` branch updates merged in.
=> Lee's Vorto migrator updates

uSync.Migrations/Migrators/BlockGrid/BlockMigrators/GridMacroBlockMigrator.cs, uSync.Migrations/Migrators/BlockGrid/Content/GridToBlockContentHelper.cs
got macro to block grid block working when you create the doc types for the macros first.
As discussed on discord
=> got macro to block grid block working 

uSync.Migrations/Migrators/Core/ColorPickerMigrator.cs
Hi @KevinJump small bug founded today
=> fix: colour picker can have 2 different aliases

uSync.Migrations/Composing/SyncMigrationsComposer.cs, uSync.Migrations/Configuration/uSyncMigrationOptions.cs, uSync.Migrations/Services/SyncMigrationService.cs
solves: https://github.com/Jumoo/uSyncMigrations/issues/170
=> feat: added possibility to turn off handlers

MyMigrations/DTGEMigrator/DTGECheckboxListMigrator.cs, MyMigrations/DTGEMigrator/DTGEDropDownMigrator.cs, MyMigrations/DTGEMigrator/DTGEMigrator.cs, MyMigrations/DTGEMigrator/DTGENestedContentMigrator.cs, MyMigrations/DTGEMigrator/DTGEPrevaluesMap.cs, MyMigrations/DTGEMigrator/README.md, MyMigrations/EmailAddressToTextboxMigrator.cs, MyMigrations/MyMigrationComposer.cs
Custom migrator for DTGE data (which is JSON-encoded and needs special handling)
=> DTGE Migrator

uSync.Migrations/Context/ContentTypeMigrationContext.cs
In my migration, we're inheriting 2 levels deep of contenttype, e.g.:
BaseContentType (= Level 1) -> ChildContentType (= Level 2) -> ChildChildContentType (= Level 3)
The composition structure looks identical in this case. If "BaseContentType" defines property "BaseA" and "ChildChildContentType" inherits "BaseA", the current code looks up the editor alias for the compositions of "ChildChildContentType" (which only includes ChildContentType) and stops there if it can't find it. It should be going further, since the alias can be found in "BaseContentType".
The fix basically travels through all composition levels until it can find the editor alias in any parent/sibling or no compositions are left to search through.
=> Fix: iterate through all composition levels to find editor alias

uSync.Migrations/Migrators/Models/SyncMigrationDataTypeProperty.cs
Proposed solution for: 
https://github.com/Jumoo/uSyncMigrations/issues/222
=> fix: ensured that we can migrate grid

uSync.Migrations/Migrators/BlockGrid/Extensions/GridConfigurationExtensions.cs, uSync.Migrations/Migrators/BlockGrid/GridToBlockGridMigrator.cs, uSync.Migrations/Migrators/BlockGrid/Models/GridConfiguration.cs, uSync.Migrations/Migrators/Community/StackedContent/StackedContentToBlockListMigrator.cs, uSync.Migrations/Migrators/Models/SyncMigrationDataTypeProperty.cs
Hey @KevinJump small issues found my last code :)
=> fix: another small bits and bobs at migrations

uSync.Migrations.Core/Configuration/CoreProfiles/BlockMigrationPlan.cs
=> Fix typo in BlockMigrationPlan name

uSync.Migrations.Migrators/Community/GibeLinkPicker/GibeLinkPickerToMultiUrlPickerMigrator.cs, uSync.Migrations.Migrators/Community/GibeLinkPicker/Models/GibeLinkPickerData.cs
Added a migrator for [Gibe.LinkPicker](https://our.umbraco.com/packages/backoffice-extensions/link-picker/)
=> Add migrator for Gibe.LinkPicker

uSync.Migrations.Core/Context/DataTypeMigrationContext.cs, uSync.Migrations.Core/Handlers/Shared/SharedContentTypeBaseHandler.cs
=> Fix - don't reset variation value in content type if its already set.

uSync.Migrations.Core/Handlers/Eight/ContentTemplateMigrationHandler.cs, uSync.Migrations.Core/uSyncMigrations.cs, uSync.Migrations.Migrators/Core/BlockListMigrator.cs
Setup migration for content templates (blueprints) of content nodes.
=> Content template migration

uSync.Migrations.Migrators/Community/ImulusUrlPicker/ImulusUrlPickerToUmbMultiUrlPickerMigrator.cs
This introduces the capability to migrate the settings configured for maximum number of items on an `Imulus.UrlPicker`
=> Update Imulus URL picker to migrate with maximum
