- MyMigrations/MyMigrationProfile.cs
- uSync.Migrations/Composing/SyncMigrationProfileCollectionBuilder.cs
- uSync.Migrations/Configuration/CoreProfiles/ContentMigrationProfile.cs
- uSync.Migrations/Configuration/CoreProfiles/EverythingMigrationProfile.cs
- uSync.Migrations/Configuration/CoreProfiles/SettingsMigrationProfile.cs
- uSync.Migrations/Configuration/Models/ISyncMigrationProfile.cs
- uSync.Migrations/Configuration/Models/MigrationProfile.cs
- uSync.Migrations/Configuration/SyncMigrationConfigurationService.cs
Keeps them in order - but lazy load them - this isn't as 'neat' as weighted, but i didn't want to load profiles and the associated code, unless you actually go near the migrations dashboard.
> profiles - keep them lazy loaded but in order

- uSync.Migrations/Migrators/Community/SwitcherToTrueFalseMigrator.cs
- uSync.Migrations/Migrators/Community/TerratypeToOpenStreetmapMigrator.cs
- uSync.Migrations/Migrators/Community/UmbracoFormsMigrator.cs
- uSync.Migrations/Migrators/Core/CheckboxListMigrator.cs
- uSync.Migrations/Migrators/Core/DatePickerMigrator.cs
- uSync.Migrations/Migrators/Core/DropdownMigrator.cs
- uSync.Migrations/Migrators/Core/LabelMigrator.cs
- uSync.Migrations/Migrators/Core/ListViewMigrator.cs
- uSync.Migrations/Migrators/Core/MediaPickerMigrator.cs
- uSync.Migrations/Migrators/Core/MemberPickerMigrator.cs
- uSync.Migrations/Migrators/Core/MultiNodeTreePickerMigrator.cs
- uSync.Migrations/Migrators/Core/MultipleTextStringMigrator.cs
- uSync.Migrations/Migrators/Core/NestedContentMigrator.cs
- uSync.Migrations/Migrators/Core/RadioButtonListMigrator.cs
- uSync.Migrations/Migrators/Core/RelatedLinksMigrator.cs
- uSync.Migrations/Migrators/Core/RichTextBoxMigrator.cs
- uSync.Migrations/Migrators/Core/SliderMigrator.cs
- uSync.Migrations/Migrators/Core/TrueFalseMigrator.cs
- uSync.Migrations/Migrators/Core/UploadFieldMigrator.cs
If we wanted to replace any of the built-in `ISyncPropertyMigrator` classes in 3rd-party, they'll need to be marked as public.
> Marks internal `ISyncPropertyMigrator` classes as public

- uSync.Migrations/Migrators/Core/MultiUrlPickerMigrator.cs
I was getting a warning in the Content migration pre-validation results:
```
there is no migrator for Umbraco.MultiUrlPicker value will be untouched but might not import correctly
```
Turns out that this was part of Umbraco v7.14+, ref: https://our.umbraco.com/packages/backoffice-extensions/multi-url-picker/
> Adds migrator for Multi-URL Picker editor

- uSync.Migrations/Handlers/ContentBaseMigrationHandler.cs
- uSync.Migrations/Models/SyncMigrationContext.cs
A proposed suggestion for idea #40. Totally open for feedback, refactoring or even rejection! 😅 
Adds (another) dictionary lookup to the `SyncMigrationContext` for ID/Key lookups. I'm not sure if there'll be performance concerns around this?
From looking at uSync v7 XML files, only Content and Media have the "id" attribute, so I've only added this to the `ContentBaseMigrationHandler` code.
> Adds ID/Key lookup to `SyncMigrationContext`

- uSync.Migrations/Handlers/ContentBaseMigrationHandler.cs
- uSync.Migrations/Handlers/MediaMigrationHandler.cs
Umbraco 8.14 introduced new default Media Types: https://umbraco.com/blog/umbraco-814-release/
This feature will check the Media node's `umbracoExtension` property value and set the corresponding Media Type alias.
---
I wasn't 100% happy having `_mediaTypeAliasForFileExtension` in the `ContentBaseMigrationHandler`, but unsure where else to have it.
> Adds support for newer Media Types

- MyMigrations/GridToBlockListMigrator.cs
- MyMigrations/MyMigrationComposer.cs
- MyMigrations/MyMigrationProfile.cs
- uSync.Migrations/Composing/SyncMigrationHandlerCollection.cs
- uSync.Migrations/Composing/SyncPropertyMigratorCollectionBuilder.cs
- uSync.Migrations/Configuration/CoreProfiles/ContentMigrationProfile.cs
- uSync.Migrations/Configuration/CoreProfiles/EverythingMigrationProfile.cs
- uSync.Migrations/Configuration/CoreProfiles/SettingsMigrationProfile.cs
- uSync.Migrations/Configuration/Models/MigrationOptions.cs
- uSync.Migrations/Configuration/SyncMigrationConfigurationService.cs
- uSync.Migrations/Handlers/ContentBaseMigrationHandler.cs
- uSync.Migrations/Handlers/ContentMigrationHandler.cs
- uSync.Migrations/Handlers/ContentTypeBaseMigrationHandler.cs
- uSync.Migrations/Handlers/ContentTypeMigrationHandler.cs
- uSync.Migrations/Handlers/DataTypeMigrationHandler.cs
- uSync.Migrations/Handlers/MediaMigrationHandler.cs
- uSync.Migrations/Handlers/MediaTypeMigrationHandler.cs
- uSync.Migrations/Migrators/Core/NestedContentMigrator.cs
- uSync.Migrations/Migrators/SyncMigratorAttribute.cs
- uSync.Migrations/Models/MigratorEditorPair.cs
- uSync.Migrations/Models/SyncMigrationContext.cs
- uSync.Migrations/Services/SyncMigrationService.cs
- uSync.Migrations/Validation/PreferedMigratorValidator.cs
- uSync.Migrations/wwwroot/uSyncMigrations/migrate.html
Move Migrators to the context, - so they can be configured by a profile. 
Idea is you can have all the migrators loaded, and then have the profiles decide which ones to use, eg. grid -> grid or grid -> blocklist. 
.eg 
you might go something like this in your `ISyncMigrationProfile`
```cs
Migrators = _migrators.GetDefault()
.Replace<GridMigrator>(typeof(GridToBlockListMigrator))
.Replace<NestedContentMigrator>(typeof(NestedContentBlockListMigrator));
```
(n.b I am making the syntax up as a i go in this PR)
need to think of the best way to present this to people, but also the best way to work out programmatically which migrator is the 'default' so when we say get us all the migrators with no config, we get the right ones.
> Move migrators to the context, so they can be configured.

- uSync.Migrations/Migrators/Community/uEditorNotesToContentmentEditorNotes.cs
- uSync.Migrations/Migrators/Community/uEditorNotesTouEditorNotes.cs
Changed the attributes on the two editor notes migrators, so they both load
but one is default -
this means they can then be "preferred" in a profile without having to replace one of them.
> Change attributes on editornotes, so they both load 

- uSync.Migrations/Services/SyncMigrationFileService.cs
Checking path stuff is OS independent.
> Make sure we use Path.DirectorySeparatorChar as needed.

- uSync.Migrations/Models/SyncMigrationContext.cs
- uSync.Migrations/Services/SyncMigrationService.cs
Not 100% sure how we should dispose of the dictionaries or lists here. 
there is some debate over settings lists and dictionaries to null actually slows down garbage collection. 
Also, i think we don't have any unmanaged resources inside the lists and dictionaries so they will be freed by the garbage collector?
the context is local to the `MigrateFiles` call so once we are outside of that then the scope is gone, and it should all be freed up? 
- So, this PR adds disposable and a using statement, but i am not sure we can actually make any difference with them?
> Make context disposable.

- uSync.Migrations/Configuration/CoreProfiles/BlockMigrationProfile.cs
- uSync.Migrations/Configuration/ISyncMigrationConfigurationService.cs
- uSync.Migrations/Configuration/Models/MigrationOptions.cs
- uSync.Migrations/Configuration/SyncMigrationConfigurationService.cs
- uSync.Migrations/Controllers/uSyncMigrationsController.cs
- uSync.Migrations/wwwroot/uSyncMigrations/Lang/en-us.xml
- uSync.Migrations/wwwroot/uSyncMigrations/dashboard.controller.js
- uSync.Migrations/wwwroot/uSyncMigrations/dashboard.html
- uSync.Migrations/wwwroot/uSyncMigrations/migration.service.js
Little change to the UI, so we are going to have migrations (Umbraco 7 -> 8/9/10/11) and Converters (inplace updates of things like block grid/blocklists...)
Converting block grid for example is going to be way easier (in both code and UI) if we do it on an existing site base - because we can access things like grid configs and automate most of it (i hope).
this change just makes that easier to present to the users.
> Update the UI - So we group profiles by migrations and conversions

- uSync.Migrations/Handlers/Seven/ContentTypeBaseMigrationHandler.cs
When the XML was being transformed, the Structure Element was being copied across, however the old DocumentType element name needed to be renamed to ContentType to stop permissions being lost.  Also added in the SortOrder, seeing as I was there!
> Childnode permissions being lost in migration

- MyMigrations/MyMigrationProfile.cs
- uSync.Migrations/Configuration/Models/MigrationOptions.cs
- uSync.Migrations/Configuration/Models/TabOptions.cs
- uSync.Migrations/Context/SyncMigrationContext.cs
- uSync.Migrations/Handlers/Eight/ContentTypeBaseMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/ContentTypeBaseMigrationHandler.cs
- uSync.Migrations/Handlers/Shared/SharedContentTypeBaseHandler.cs
- uSync.Migrations/Services/SyncMigrationService.cs
Allows for changing the name and alias of a tab, merging the properties of one tab into another and deleting a tab.  Doesn't do sorting though!  At present, only been tested on a v7 migration.
> Manipulate tabs on migration

- uSync.Migrations/Migrators/Community/RjpMultiUrlPickerToUmbMultiUrlPickerMigrator.cs
This works for me based on the real data that I see in a Umbraco 7.4.3 site and [what GitHub shows](https://github.com/rasmusjp/umbraco-multi-url-picker/blob/6dc138ddfa6ce3d3afbade7e18697b7488f71bdb/src/RJP.MultiUrlPicker/Models/LinkDto.cs) (that don't entirely match).
The Url is only included where a Udi is not available, as per the built-in MultiUrlPicker save format
> Addition of RJP.MultiUrlPicker migrator to built-in MultiUrlPicker

- uSync.Migrations/Helpers/MarkdownEditorHelper.cs
- uSync.Migrations/Migrators/Community/CrumpledCharLimitEditorToTextboxMigrator.cs
- uSync.Migrations/Migrators/Community/CrumpledMarkdownEditorToRichTextEditorMigrator.cs
- uSync.Migrations/Migrators/Models/CrumpledMarkDown.cs
- uSync.Migrations/Migrators/Models/CrumpledMarkdownEditor.cs
Primarily used internally, these are migrators for data types that were constructed by Crumpled Dog in the past.  They might be useful for anyone who has picked them up or finds them in an inherited project!
> Migrators for Crumpled Dog produced data types

- uSync.Migrations/Handlers/Eight/ContentTypeBaseMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/ContentTypeBaseMigrationHandler.cs
- uSync.Migrations/Handlers/Shared/SharedContentTypeBaseHandler.cs
This pull request fixes issue #89. My approach was to keep a reference to the original XElement (`source`), and if a **tab** is discovered without a key value, create the GUID using the `source alias`. 
Please closely review this PR. I'm not a C# developer. I'd be happy to receive any feedback & suggestions, as well as make improvements until this can be merged.
Thank you,
> Tabs Without Keys Need a Unique Key (GUID)

- uSync.Migrations/Migrators/Community/RjpMultiUrlPickerToUmbMultiUrlPickerMigrator.cs
RJP Picker migrator had no support for converting a content Id to a Udi. Resolved.
> Support ID resolution to Guid using SyncMigrationContext.GetKey()

- uSync.Migrations/Migrators/Core/ContentPickerMigrator.cs
My v7 files have Content Picker data saved as a Guid only. 
e.g.
```
<?xml version="1.0" encoding="utf-8"?>
<Settings guid="17989892-0abc-4241-ad44-1d29d6d207f2" id="1123" nodeName="Settings" isDoc="" updated="2022-12-05T10:47:45.8200000Z" parentGUID="e7ea6873-8661-48ee-8741-e8e9e91264ab" nodeTypeAlias="Settings" templateAlias="" sortOrder="5" published="true" isBlueprint="false">
<footer>3838ffde-5519-4ed5-8f75-241a40293d8b</footer>
<header>ac0c2245-9e48-4257-96dd-f45b265a8e40</header>
</Settings>
```
The property then appears empty in the backoffice after migration.
This simple update converts any data that is a straight Guid in to a Udi
> ContentPicker1Migrator support for Keys not UDIs

- uSync.Migrations/Migrators/Core/NestedContentMigrator.cs
I've got empty keys in my old v7 data, which works in the backoffice but breaks on published content model ctor.
Enforcing a key resolves the issue.
> NC key can be empty

- uSync.Migrations/Handlers/Seven/ContentTypeBaseMigrationHandler.cs
As it stands, when generating the migrated uSync definition for a Content Type in Umbraco 7, the tabs section has `Alias` and `Type` as attributes:
```
<GenericProperties>
<GenericProperty>
<Key>0270d8ba-00c8-4e44-90f2-b4a485ae72da</Key>
<Name>Description</Name>
<Alias>description</Alias>
<Definition>1f540f32-a19a-4fd9-abd1-59886381f1e3</Definition>
<Type>Umbraco.TinyMCEv3</Type>
<Mandatory>false</Mandatory>
<Validation></Validation>
<Description><![CDATA[]]></Description>
<SortOrder>1</SortOrder>
<Tab Alias="Content" Type="Tab">Content</Tab>
<Variations>Nothing</Variations>
<MandatoryMessage></MandatoryMessage>
<ValidationRegExpMessage></ValidationRegExpMessage>
<LabelOnTop>false</LabelOnTop>
</GenericProperty>
</GenericProperties>
<Tabs>
<Tab Alias="Content" Type="Tab"> …
```
> Fix tab structure in migrated Content Type definition files (Umbraco 7)

- uSync.Migrations/Migrators/Models/NuPickers/NuPickersEnumConfig.cs
- uSync.Migrations/Migrators/Models/NuPickers/NuPickersSqlConfig.cs
- uSync.Migrations/Migrators/Models/NuPickers/NuPickersXmlConfig.cs
To facilitate creating custom migrators without the need to duplicate these models
> Make NuPickers models public

- uSync.Migrations/Composing/SyncMigrationsComposer.cs
- uSync.Migrations/Configuration/Models/MigrationOptions.cs
- uSync.Migrations/Context/ContentTypeMigrationContext.cs
- uSync.Migrations/Context/DataTypeMigrationContext.cs
- uSync.Migrations/Context/SyncMigrationContext.cs
- uSync.Migrations/Extensions/ContentTypeExtensions.cs
- uSync.Migrations/Handlers/Eight/ContentTypeBaseMigrationHandler.cs
- uSync.Migrations/Handlers/Eight/ContentTypeMigrationHandler.cs
- uSync.Migrations/Handlers/Eight/MediaTypeMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/ContentTypeBaseMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/ContentTypeMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/MediaTypeMigrationHandler.cs
- uSync.Migrations/Handlers/Shared/SharedContentBaseHandler.cs
- uSync.Migrations/Handlers/Shared/SharedContentTypeBaseHandler.cs
- uSync.Migrations/Handlers/Shared/SharedDataTypeHandler.cs
- uSync.Migrations/Migrators/Community/Archetype/ArchetypeMigrationConfigurerCollectionBuilder.cs
- uSync.Migrations/Migrators/Community/Archetype/ArchetypeToBlockListMigrator.cs
- uSync.Migrations/Migrators/Community/Archetype/DefaultArchetypeMigrationConfigurer.cs
- uSync.Migrations/Migrators/Community/Archetype/IArchetypeMigrationConfigurer.cs
- uSync.Migrations/Migrators/Community/Archetype/Models/ArchetypeFieldsetModel.cs
- uSync.Migrations/Migrators/Community/Archetype/Models/ArchetypeModel.cs
- uSync.Migrations/Migrators/Community/Archetype/Models/ArchetypePreValue.cs
- uSync.Migrations/Migrators/Community/Archetype/Models/ArchetypePreValueFieldset.cs
- uSync.Migrations/Migrators/Community/Archetype/Models/ArchetypePreValueFieldsetGroup.cs
- uSync.Migrations/Migrators/Community/Archetype/Models/ArchetypePreValueProperty.cs
- uSync.Migrations/Migrators/Community/Archetype/Models/ArchetypePropertyModel.cs
- uSync.Migrations/Models/DataTypeInfo.cs
- uSync.Migrations/Models/NewContentTypeProperty.cs
- uSync.Migrations/Services/SyncMigrationService.cs
Adds a migrator for Archetype. This required some refactoring of the main uSync Migrations code - I've added some comments to the PR to explain further.
> Add Archetype migrator

- uSync.Migrations/Context/ContentTypeMigrationContext.cs
- uSync.Migrations/Context/DataTypeMigrationContext.cs
- uSync.Migrations/Context/MigratorsContext.cs
- uSync.Migrations/Handlers/Shared/SharedContentBaseHandler.cs
- uSync.Migrations/Handlers/Shared/SharedContentTypeBaseHandler.cs
- uSync.Migrations/Handlers/Shared/SharedDataTypeHandler.cs
- uSync.Migrations/Migrators/Community/EpiphanySeoMetadataToSeparateFields.cs
- uSync.Migrations/Migrators/ISyncPropertyMigrator.cs
- uSync.Migrations/Migrators/Models/SplitPropertyContent.cs
- uSync.Migrations/Migrators/Models/SplitPropertyInfo.cs
- uSync.Migrations/Models/EditorAliasInfo.cs
This adds a new migrator interface (`ISyncPropertySplittingMigrator`) for migrators that split a single property into multiple. The Epiphany.SeoMetadata package stored meta Title, Description, UrlName and NoIndex in a blob of JSON. This migrator splits this JSON into separate properties.
> Add migration from Epiphany.SeoMetadata to separate properties

- uSync.Migrations/Migrators/Core/RelatedLinksMigrator.cs
Content Edition writes out RelatedLinks content with Guids instead of int ids, for ease of uniqueness comparison beetween environments, however it doesn't put the Guids in "" so in this context when we come to deserialise them, it's invalid JSON. This fix just pragmatically wraps any guids in double quotes before it is deserialised
> Fix RelatedLinks migration

- uSync.Migrations/Migrators/Core/RelatedLinksMigrator.cs
it can be inconsistant with the qoutes on the GUIDs for related links, 
it means sometimes we get "GUID" and others ""GUID"". 
so this just replaces "" with " in the value - this 'should' fix it.
> Fix ? for #122

- MyMigrations/MyMigrationProfile.cs
- uSync.Migrations/Configuration/Models/MigrationOptions.cs
- uSync.Migrations/Context/MigratorsContext.cs
- uSync.Migrations/Handlers/MigrationHandlerBase.cs
- uSync.Migrations/Handlers/Shared/SharedContentBaseHandler.cs
- uSync.Migrations/Services/SyncMigrationStatusService.cs
Adds the ability to set migrators by property name,. (either globally or at a contentType level).
In your own plan - code. add the following: 
```
PropertyMigrators = new Dictionary<string, string>()
{
// use the NestedToBlockListMigrator For myProperty in the 'MyContentType' contentType
{ "myContentType_myProperty", nameof(NestedToBlockListMigrator) }, 
// Convert all properties called myGridProperty to blocklist 
{ "myGridProperty", nameof(GridToBlockListMigrator) }
},
```
> Migrators by property name.

- MyMigrations/Mergers/SimpleMergePlan.cs
- MyMigrations/Mergers/SimpleStringMerger.cs
- uSync.Migrations/Composing/SyncMigrationsComposer.cs
- uSync.Migrations/Composing/SyncPropertyMergingCollectionBuilder.cs
- uSync.Migrations/Configuration/Models/MigrationOptions.cs
- uSync.Migrations/Context/ContentMigrationContext.cs
- uSync.Migrations/Context/MigratorsContext.cs
- uSync.Migrations/Extensions/XElementExtensions.cs
- uSync.Migrations/Handlers/Shared/SharedContentBaseHandler.cs
- uSync.Migrations/Migrators/ISyncPropertyMigrator.cs
- uSync.Migrations/Migrators/Models/SyncMigrationContentProperty.cs
- uSync.Migrations/Models/MergingPropertiesConfig.cs
- uSync.Migrations/Services/SyncMigrationService.cs
- uSync.Migrations/Services/SyncMigrationStatusService.cs
- uSyncMigrationSite/uSyncMigrationSite.csproj
*WIP - still a little bit to do around - datatype generation* 
This PR adds the ability to write property merging code, (via a `ISyncPropertyMergingMigrator`)
Merging will likely be very project specific, as you need to know the content type and the property names you want to merge , so it's something that you will configure on a project by project basis, but in theory this lets you do things like merge a load of properties into a single property (e.g a blockgrid). 
there are two parts to using a Merger. 
At a simple level this class will then get a list of property values, and is expected to return a string representing the merged properties,  for a complex property this will likely be a JSON string. 
e.g the SimpleStringMerger in this PR does this. 
```cs
public string …
```
> WIP - Merging property handlers.

- uSync.Migrations/Migrators/Community/NuPickersToContentmentDataListBase.cs
- uSync.Migrations/Migrators/Community/NuPickersXPathCheckboxPickerToContentmentDataList .cs
- uSync.Migrations/Migrators/Community/NuPickersXPathDropdownPickerToContentmentDataList.cs
Changing an XPath string expression from '//' to '$root/' changes its behaviour from select descendants to select children.
Using '$root//' works as does the original '//' as both are valid XPath expressions, but chose to remove the string replacement and keep the original expression as had no problems with it in the destination Contentment dataTypes - although perhaps I've missed where it errors ? (if so, could add the '$root' prefix)
Also added handling of non-standard token '$ancestorOrSelf' which gets converted into a Contentment '$current' token.
> Fixed XPath string manipulation for NuPickers

- uSync.Migrations/Migrators/Community/StackedContentToBlockListMigrator.cs
When the stacked content migrator was migrating any values nested inside, it wasn't respecting the preferred migrator settings (it was just taking the first applicable migrator). This changeset fixes this issue so that preferred migrators are respected.
> Fix stacked content migrator to respect preferred migrators

- uSync.Migrations/Migrators/Community/StackedContentToBlockListMigrator.cs
Stacked Content prevalue for max items stored "no maximum" as 0, whereas for BlockList "no maximum" should be stored as null
> Fix stacked content max items = 0 migration issue

- uSync.Migrations/Migrators/Community/Archetype/ArchetypeToBlockListMigrator.cs
- uSync.Migrations/Migrators/Community/StackedContentToBlockListMigrator.cs
- uSync.Migrations/Migrators/Core/NestedContentMigrator.cs
- uSync.Migrations/Migrators/Optional/NestedToBlockListMigrator.cs
Nested DateTime values (like this 2022-12-31T00:00:00) were getting parsed by the DeserializeObject call, and later converted back to string using simply `.ToString()` which used the default string formatting for the current culture (e.g. 12/31/2021 12:00:00 AM). This format later resulted in errors after import when trying to build the Examine index. This changeset prevents DateTimes from being parsed, so the date/time values stay as a string, which is how the Umbraco.DateTime migrator expects the value.
> Fix issue where nested DateTime format gets messed up

- uSync.Migrations/Migrators/Community/StackedContentToBlockListMigrator.cs
- uSync.Migrations/Migrators/Core/NestedContentMigrator.cs
- uSync.Migrations/Migrators/Optional/NestedToBlockListMigrator.cs
When an element type has a composition type, this composition type does not getting imported as an element type. This causes an error later, when generating models.
> Fix to ensure element type compositions are marked as element types

- uSync.Migrations/Migrators/Core/RichTextBoxMigrator.cs
There are subtle differences in the config options from v7, e.g. `"ace"` instead of `"code"`. This patch aligns them.
> RichText/TinyMCE - config migrator

- uSync.Migrations/Migrators/Core/NestedContentMigrator.cs
For those cases when a custom migrator is targeting a specific doctype/property-alias.
> NestedContent migrator - adds ContentType/PropertyType alias to inner migrator lookup

- uSync.Migrations/Handlers/Seven/LanguageMigrationHandler.cs
I'd noticed a couple of cultures having the same LCID, 4096, 19465. Which meant that when generating a Guid, there'd be a key clash. I've switched the code to use the alias (ISO culture code) to generate the Guid from.
> Language handler - LCID was unreliable, changed to culture code

- uSync.Migrations/Extensions/ContentTypeExtensions.cs
- uSync.Migrations/Handlers/Shared/SharedContentTypeBaseHandler.cs
- uSync.Migrations/Models/NewContentTypeInfo.cs
- uSync.Migrations/Models/NewContentTypeProperty.cs
When adding new content types to the context, this changeset allows specifying compositions and tabs to be added to the new content types. Previously no compositions were used and there was a single hard-coded "Block" tab group.
This is a feature that I'd like to use in [this BlockListSettings addon](https://github.com/EtchUK/Etch.uSyncMigrations.BlockListSettings) I've been working on.
> Allow setting compositions and tabs for new content types

- uSync.Migrations/Handlers/MigrationHandlerBase.cs
Skip the '<empty>' files when doing a migration
> Fixes : #173 & #187 - Skip "empty" files during migration.

- GETTING-STARTED.md
I just tried to install the v7 packer on a v7.13.2 site to discover that it won't install as requires a minimum Umbraco version of 7.15.10
Assuming that this _has_ to be the minimum version supported, I have added a note to the Getting Started docs.
What's the minimum version for the v8 packer, as I could get that added too?
I assume that if you are on a site lower than the minimum you need to go to Our and download the appropriate 'Content Edition' package? I could add those words too.
> Packer v7 min version guidance

- uSync.Migrations/Migrators/BlockGrid/Config/GridToBlockGridConfigContext.cs
- uSync.Migrations/Migrators/BlockGrid/Config/GridToBlockGridConfigLayoutBlockHelper.cs
- uSync.Migrations/Migrators/BlockGrid/Content/GridToBlockContentHelper.cs
- uSync.Migrations/Migrators/BlockGrid/Extensions/GridConfigurationExtensions.cs
This fixes a couple of issues I encountered while migrating a DTGE based site.
e615325 If you have an editor, using a regex to define allowed content types, it will now migrate into a new block type per content type matched.
c23ae99 If your root section only has one area, as wide as the complete grid, the layout block type is not created, but the migrator will still try to create the layout block. This fails, as the layout block gets a content type of Guid.Empty - as the block type and content type isn't created.
2ab119d If I understand correctly, layouts with full width are counted as root sections, and not converted into layout blocks. If you have editors only allowed in these full width columns, they are not being created correctly.
> DTGE fixes

- uSync.Migrations/Migrators/Optional/NestedToBlockListMigrator.cs
When converting grid with DTGE with Nested Content inside, for some reason it runs the migration of Nested Content properties twice. Should probably be fixed in another way, but I got around it, by checking the value, as in this PR.
You could do the check like in Grid to BlockGrid, but I am unsure how it would cope with Nested Content inside of Nested Content.
> Fix for Nested Content to Block List in Grid

- uSync.Migrations/Handlers/Shared/SharedDataTypeHandler.cs
- uSync.Migrations/Migrators/Community/Archetype/ArchetypeToBlockListMigrator.cs
- uSync.Migrations/Migrators/Community/VortoMapper.cs
- uSync.Migrations/Models/DataTypeInfo.cs
Hi @KevinJump,
found interesting issue with that we rely on datatype service in context, datatypes getting migrated, but content is not as we cannot fnd migrator for editor alias :)
> fix: ensured that we can rerun migrations after having db up and running first migration

- uSync.Migrations/Extensions/SyncMigrationContentPropertyExtensions.cs
- uSync.Migrations/Handlers/Shared/SharedContentBaseHandler.cs
- uSync.Migrations/Migrators/BlockGrid/Content/GridToBlockContentHelper.cs
- uSync.Migrations/Migrators/BlockGrid/GridToBlockGridMigrator.cs
Adds some more property migration logging.
Longer term i think a reworking of the migrators so they can return diagnostics would greatly help people working out what has or hasn't gone well with a migration. 
we do have a lot of reporting it could be sown in.
> More debug logging in property migrations

- uSync.Migrations/Migrators/Community/RobotsMetaEditorToContentmentDataList.cs
This adds a migrator for [robotsMetaEditor](https://github.com/mikkelhm/Umbraco-robots-meta-tag-property-editor) to Contentment Data List with a user defined source, and a radio button list as the display.
I've added the `[SyncMigratorVersion(7, 8)]` because it wont run on my machine without it. Don't know if its necessary, or just me :)
> Migrator for robotsMetaEditor to Contentment Data List

- uSync.Migrations/Migrators/Community/SkttlHtmlEditorToContentmentCodeEditor.cs
This adds a migrator for [skttl.HtmlEditor](https://github.com/skttl/skttl.HtmlEditor) to Contentment Code Editor.
I've added the [SyncMigratorVersion(7, 8)] because it wont run on my machine without it. Don't know if its necessary, or just me :)
> Migrator for skttl.HtmlEditor to Contentment Code Editor

- uSync.Migrations/Migrators/BlockGrid/GridToBlockGridMigrator.cs
I found out (at least in my migration), that I had a bunch of DTGEs in my content, where the view property was just null. This caused the Migration to fall back to the default grid editor migrator, and then it failed, because it couldn't find the contenttype (as it was looking for eg. BlockElement_spot).
The grid editor could look like this:
```json
{
"value": {
"id": "4467644c-b930-e6be-61b7-9867f8baf26c",
"dtgeContentTypeAlias": "spot",
"value": {
"name": "Spot",
"image": "",
"title": "Skal du fakturere et af selskaberne?",
"description": null,
"link": [],
"hideImage": "0"
}
},
"editor": {
"alias": "spot",
"view": null
},
"styles": null,
"config": null
},
```
So I added some code, to run through the deserialized grid value, and find controls with null in view, and a dtgeContentTypeAlias …
> Some times DTGEs has no view specified

- uSync.Migrations/Context/DataTypeMigrationContext.cs
Issue was occurring due to the data type not being present causing the `FirstOrDefault` to return an empty item with an empty GUID. Solution was to add a check to see if the value returned from `FirstOrDefault` isn't null.
> Fix SEO metadata migrator outputting empty GUID for definition node

- uSync.Migrations/Migrators/Core/DatePickerMigrator.cs
Umbraco.Date no longer exists in Umbraco, so Umbraco.Date editors can be migrated to Umbraco.DateTime. Without this change, Umbraco.Date editors remain as Umbraco.Date which doesn't exist and causes issues when trying to use such editors in Umbraco 9+.
> fix: ensure Umbraco.Date editors are migrated to Umbraco.DateTime

- uSync.Migrations/Configuration/Models/MigrationOptions.cs
- uSync.Migrations/Context/ContentTypeMigrationContext.cs
- uSync.Migrations/Handlers/Eight/ContentBaseMigrationHandler.cs
- uSync.Migrations/Handlers/Eight/ContentTypeBaseMigrationHandler.cs
- uSync.Migrations/Handlers/MigrationHandlerBase.cs
- uSync.Migrations/Handlers/Seven/ContentBaseMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/ContentTypeBaseMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/DataTypeMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/DictionaryMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/LanguageMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/MacroMigrationHandler.cs
- uSync.Migrations/Handlers/Seven/TemplateMigrationHandler.cs
- uSync.Migrations/Handlers/Shared/SharedContentBaseHandler.cs
- uSync.Migrations/Handlers/Shared/SharedContentTypeBaseHandler.cs
- uSync.Migrations/Handlers/Shared/SharedDataTypeHandler.cs
- uSync.Migrations/Handlers/Shared/SharedHandlerBase.cs
- uSync.Migrations/Handlers/Shared/SharedTemplateHandler.cs
- uSync.Migrations/Migrators/BlockGrid/BlockMigrators/DocTypeGridEditorBlockMigrator.cs
- uSync.Migrations/Migrators/BlockGrid/Content/GridToBlockContentHelper.cs
- uSync.Migrations/Migrators/BlockGrid/GridToBlockGridMigrator.cs
- uSync.Migrations/Migrators/Core/MultiNodeTreePickerMigrator.cs
- uSync.Migrations/Migrators/Core/NestedContentMigrator.cs
- uSync.Migrations/Migrators/Optional/NestedToBlockListMigrator.cs
- uSync.Migrations/Services/SyncMigrationService.cs
- uSync.Migrations/Services/SyncMigrationStatusService.cs
Based on comments from #200.
I've taken over the work that @bielu started. We found some issues with his implementation - where the replacement aliases weren't being used in all places. This PR fixes those issues and addresses the feedback from #200.
I tried to cover any other places that content type aliases are referenced such as in MNTP config, but it's possible there are others I've missed. Hopefully this is a good enough starting point.
> Ability to rename content types

- uSync.Migrations/Migrators/BlockGrid/BlockMigrators/ISyncBlockMigrator.cs
Just a small thing that came up when I was working on some specialised migrators for macros, I've tried to follow how this was done for the property migrators to make sure it's all cohesive.
> feat: allow for overrides on grid migrators

- uSync.Migrations/Migrators/Community/RjpMultiUrlPickerToUmbMultiUrlPickerMigrator.cs
Hi Kevin,
I looked at usync and not sure how to fix it there, but for migration it is pretty easy :)
Partially solves: https://github.com/Jumoo/uSyncMigrations/issues/220
> fix: ensured that if content is not presented to not populate it as it breaks usync

- uSync.Migrations/Context/SyncMigrationContext.cs
While doing our migration we wanted to be able to assign the v7 Umbraco numeric node ID to a property on some documents, but I couldn't figure out an easy way to do that. This change allows the ID to be obtained from the _idKeyMap by passing in the node Key.
> Make v7 node ID accessible in SyncMigrationContext._idKeyMap

- uSync.Migrations/Migrators/BlockGrid/Composition/BlockGridMigratorComposer.cs
- uSync.Migrations/Migrators/BlockGrid/Config/GridToBlockGridConfigLayoutBlockHelper.cs
- uSync.Migrations/Migrators/BlockGrid/Config/GridToBlockGridConfigLayoutSettingsHelper.cs
- uSync.Migrations/Migrators/BlockGrid/Content/GridToBlockContentHelper.cs
- uSync.Migrations/Migrators/BlockGrid/Extensions/GridConventions.cs
- uSync.Migrations/Migrators/BlockGrid/Extensions/GridToBlockGridNameExtensions.cs
- uSync.Migrations/Migrators/BlockGrid/GridToBlockGridMigrator.cs
- uSync.Migrations/Migrators/BlockGrid/Models/GridModels.cs
- uSync.Migrations/Migrators/BlockGrid/SettingsMigrators/GridViewPropertyBooleanMigrator.cs
- uSync.Migrations/Migrators/BlockGrid/SettingsMigrators/IGridSettingsViewMigrator.cs
Builds off of changes by @bielu (thank you!) 
Adds in some rough functionality to convert config and styles from the legacy grid to the BlockGrid & acts as a start for settings conversion. This implementation only handles the config/styles in the Layout layer (row) but perhaps similar implementations can be adopted for other layers.
It does this by:
Content Types
Reading config/styles & merging them (they have the same JSON data structure, afaik these are split up in the legacy grid for permissions based settings).
Create datatypes called BlockGridSettings_ for each grid.
Add the above block grid settings to each of the layouts for that grid. (It is safe to assume that all the layouts can have these as that is the behaviour of the legacy grid).
Nothing is done with modifier & prevalues as …
> feat: block grid settings

- dist/build-package.ps1
- uSync.Migrations.Core/Handlers/Shared/SharedDataTypeHandler.cs
Fixes a typo in the project folder name which will prevent the nuget package from being built
> Fixes a typo in the project folder name in package build script & fixes a bug with migrations causes by recent changes

- uSync.Migrations.Client/wwwroot/App_Plugins/uSyncMigrations/backoffice/uSyncMigrations/dashboard.controller.js
- uSync.Migrations.Client/wwwroot/App_Plugins/uSyncMigrations/backoffice/uSyncMigrations/dashboard.html
- uSync.Migrations.Core/Handlers/Eight/ContentBaseMigrationHandler.cs
- uSync.Migrations.Core/Handlers/Eight/DataTypeMigrationHandler.cs
- uSync.Migrations.Core/Migrators/Models/SyncMigrationContentProperty.cs
- uSync.Migrations.Migrators/BlockGrid/GridToBlockGridMigrator.cs
This adds some logic in the Content migrator for v8 (and above). so we can actually migrate variant content. 
Variant content can't be migrated, if you want to also use a splitting, or merging migrator, but as at the moment, vorto is the only real splitting migrator, and that's v7, we are going to live with this restriction.
> Make it so we can migrate variant properties, (for v8 -> v.x migrations.

- uSync.Migrations.Core/Handlers/Shared/SharedContentBaseHandler.cs
In v8 usync files - most nodeName and published already have cultured values.
This request will ensure that there are no duplicates
> Added check for cultured name or published values - to ensure no duplicates

- uSync.Migrations.Migrators/BlockGrid/Config/GridToBlockGridConfigBlockHelper.cs
Added a check for if contentTypeElement already is added to the contentBlocks.
This fixes a error I got in the converting.
Maybe this also fix: #255 ? - but not sure..
> Prevent adding blocks that already added to the grid blocks

- uSync.Migrations.Core/Context/ContentTypeMigrationContext.cs
- uSync.Migrations.Core/Context/DataTypeMigrationContext.cs
- uSync.Migrations.Core/Handlers/Shared/SharedContentTypeBaseHandler.cs
- uSync.Migrations.Core/Handlers/Shared/SharedDataTypeHandler.cs
- uSync.Migrations.Core/Models/EditorAliasInfo.cs
This pull request fixes a problem with property types are not updated on contentTypes (after they have been updated on datatypes).
Maybe not the most elegant solution, but it works. of course you are welcome to correct.
> Fixes that PropertyType is not updated on contentTypes

- uSync.Migrations.Core/Context/DataTypeMigrationContext.cs
- uSync.Migrations.Core/Extensions/ContentTypeExtensions.cs
- uSync.Migrations.Core/Extensions/DataTypeExtensions.cs
- uSync.Migrations.Core/Handlers/Shared/SharedContentTypeBaseHandler.cs
- uSync.Migrations.Core/Handlers/Shared/SharedDataTypeHandler.cs
- uSync.Migrations.Core/Models/NewContentTypeProperty.cs
- uSync.Migrations.Core/Models/NewDataTypeInfo.cs
- uSync.Migrations.Migrators/BlockGrid/BlockMigrators/GridBlockMigratorSimpleBase.cs
- uSync.Migrations.Migrators/BlockGrid/Config/GridToBlockGridConfigContext.cs
- uSync.Migrations.Migrators/BlockGrid/Config/GridToBlockGridConfigLayoutBlockHelper.cs
- uSync.Migrations.Migrators/BlockGrid/Config/GridToBlockGridConfigLayoutSettingsHelper.cs
- uSync.Migrations.Migrators/BlockGrid/Content/GridToBlockContentHelper.cs
- uSync.Migrations.Migrators/BlockGrid/Extensions/GridConfigurationExtensions.cs
- uSync.Migrations.Migrators/BlockGrid/Extensions/GridConventions.cs
- uSync.Migrations.Migrators/BlockGrid/Extensions/GridToBlockGridNameExtensions.cs
- uSync.Migrations.Migrators/BlockGrid/GridToBlockGridMigrator.cs
- uSync.Migrations.Migrators/BlockGrid/Models/GridModels.cs
- uSync.Migrations.Migrators/BlockGrid/SettingsMigrators/GridViewPropertyImageMigrator.cs
- uSync.Migrations.Migrators/BlockGrid/SettingsMigrators/GridViewPropertyNumberMigrator.cs
- uSync.Migrations.Migrators/BlockGrid/SettingsMigrators/GridViewPropertyRadioButtonListMigrator.cs
- uSync.Migrations.Migrators/BlockGrid/SettingsMigrators/IGridSettingsViewMigrator.cs
- uSync.Migrations.Migrators/Optional/NestedToBlockListMigrator.cs
Added new settings migrators for:
- imagepicker
- number
- radiobuttonlist
The radio button list requires a new data type, so it's more complex than the others. The grid allows labels and values in a radio button list setting to be different, but that's not possible in a standard Umbraco radio button list, so I'm only keeping the labels. You'd need to add some code to convert from labels to values before outputting in a view.
Also added migration of column settings from grid to block grid. There's no way to add settings to a block grid area, so if there are settings present on a column they are added to an "Area Settings" component which is added as the first component in the area.
> New grid view property migrators, migrate column settings from grid to block grid

- uSync.Migrations.Migrators/Community/TerraType/TerratypeToGMapsMigrator.cs
- uSync.Migrations.Migrators/Community/TerraType/TerratypeToOpenStreetmapMigrator.cs
The new migrator is non-default and I have specified the existing OSM one to be default.
> Add a Terratype to Our.Umbraco.GMaps Migrator

- uSync.Migrations.Migrators/BlockGrid/Config/GridToBlockGridConfigBlockHelper.cs
- uSync.Migrations.Migrators/BlockGrid/Content/GridToBlockContentHelper.cs
When using areas that have settings, rather than add an additional "Area Settings Block" as the first block, this PR will add the respective settings and their content values to each layout area directly, so that you have a Block with the proper settings.
> Add Block Settings Directly To Layout Blocks
